STORED_INDEX = "token-tree.pickle"
N_GRAM_INDEX_LENGTH = 2
DB_ECHO = False
STEM_ENABLED = False
STATS_LIMIT = 100
# THE INTERVAL BETWEEN SAVING THE INDEX
# INTO THE PICKLE FILE IN SECONDS
SAVE_INTERVAL = 60
# ALIASES FOR USING AND OR NOT OPERATIONS
# IN QUERIES.
AND_OPERATION = "<and>"
OR_OPERATION = "<or>"
NOT_OPERATION = "<not>"